version: "3"
services:

  db:
    image: mysql
    container_name: db_skill-matrice
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - dev

networks:
  dev:

volumes:
  db-data:
